### ISSUE TITLE
Git flow

### ISSUE THREAD

**Issue by thesbros** [pkmn-world/pkmn-world#9]
Looks like we have [git flow](http://nvie.com/posts/a-successful-git-branching-model/) layout, but currently everything is being merged into master. Correct way would to be merge everything into develop, and once there is a release branch, to merge it into master.

**Comment by bastuijnman** [comment]
We're not specifically using git flow, I just used the feature prefix because I like to do so myself.

I think git flow might add a lot of overhead regarding managing branches and releases, especially in the start of the project.

Merging into master as quick as possible and creating new releases as quick as possible would have my preference.

**Comment by koesie10** [comment]
The develop branch was not used as in git flow by @ThomasShaped, as I can see he just used it for a new pull request. We could just tag a commit when we create a new release, no need for separate develop and master branches.

**Comment by thesbros** [comment]
I assume we should just delete the develop branch then? As it was only used for one PR, and it has the same name as the git flow branch, which might be confusing to some people.

**Comment by bastuijnman** [comment]
Yeah I think it's fine to delete it

**Comment by bastuijnman** [comment]
Closed develop
